cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('list/', views.list, name='list'),
    path('delete/<int:cart_item_id>/', views.delete, name='delete'),
    path('modify/<int:cart_item_id>/', views.modify, name='modify'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:product_id>/', views.product_detail, name='detail'),
    path('<int:product_id>/question/create/', views.question_create, name='question_create'),
    path('<int:product_id>/question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    path('<int:product_id>/question/modify/<int:question_id>', views.question_modify, name='question_modify'),
    path('<int:product_id>/pick/', views.product_pick, name='pick'),
    path('<int:product_id>/picked/', views.product_unpick, name='unpick'),
    path('admin_api/', views.AdminApiProductListCreateView.as_view(), name='admin_api'),
    path('admin_api/<int:pk>/', views.AdminApiProductRetrieveUpdateDestroyView.as_view(), name='admin_api_item'),
    path('admin_api/<int:product_id>/reals/', views.AdminApiProductRealListCreateView.as_view(), name='admin_api_reals'),
]

qna/urls.py
app_name = 'qna'

urlpatterns = [

]

cart/models.py
# Create your models here.

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from accounts.models import User
from products.models import ProductReal


class CartItem(models.Model):
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return f"{self.id}, {self.product_real}"

    reg_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_real = models.ForeignKey(ProductReal, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField('수량', default=1,
                                                validators=[MinValueValidator(1), MaxValueValidator(100)])

cart/forms.py
from django.forms import ModelForm

from cart.models import CartItem
from products.models import ProductReal


class ProductCartAddForm(ModelForm):
    def __init__(self, *args, **kwargs):
        product_id: int = kwargs.pop('product_id', '')
        super().__init__(*args, **kwargs)
        self.fields['product_real'].label = "옵션"

        if product_id:
            product_reals = ProductReal.objects.filter(product_id=product_id)
            product_real_choices = [(i.id, f'{i.option_1_display_name} / {i.option_2_display_name}') for i in
                                    product_reals]

            self.fields['product_real'].choices = product_real_choices

        self.fields['quantity'].widget.attrs.update(min=1)
        self.fields['quantity'].widget.attrs.update(max=100)

    class Meta:
        model = CartItem
        fields = ['product_real', 'quantity']

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import HttpRequest
# Create your views here.
from django.shortcuts import redirect, render, get_object_or_404, resolve_url
from django.views.decorators.http import require_POST, require_GET

from cart.forms import ProductCartAddForm
from cart.models import CartItem
from products.models import ProductReal


@login_required
@require_POST
def add(request: HttpRequest):
    product_real: ProductReal = ProductReal.objects.get(id=request.POST.get('product_real'))
    form = ProductCartAddForm(request.POST)

    if form.is_valid():
        cart_items_qs: QuerySet = CartItem.objects.filter(user=request.user, product_real=product_real)

        if cart_items_qs.exists():
            old_cart_item = cart_items_qs.first()
            old_cart_item.quantity += int(form.cleaned_data['quantity'])
            old_cart_item.save()
        else:
            cart_item = form.save(commit=False)
            cart_item.user = request.user
            cart_item.save()

        name = f'{product_real.product.display_name}/{product_real.option_1_display_name}/{product_real.option_2_display_name}'

        messages.success(request,
                         f"장바구니에 상품({name})이 {form.cleaned_data['quantity']}개 추가되었습니다. <a href='{resolve_url('cart:list')}'>장바구니로 이동</a>")
        return redirect('products:detail', product_real.product.id)

    messages.error(request, form['quantity'].errors, 'danger')
    return redirect('products:detail', product_real.product.id)


@login_required
@require_GET
def list(request: HttpRequest):
    cart_items = CartItem \
        .objects \
        .select_related('product_real', 'product_real__product', 'product_real__product__market', 'product_real__product__cate_item') \
        .filter(user=request.user)

    return render(request, "cart/list.html", {
        "cart_items": cart_items
    })


@login_required
@require_POST
def delete_items(request: HttpRequest):
    ids = map(int, request.POST.get('ids').split(','))
    cart_items = CartItem.objects.filter(id__in=ids)

    for cart_item in cart_items:
        if cart_item.user != request.user:
            raise PermissionError()
        cart_item.delete()

    messages.success(request, "해당 장바구니 품목들이 삭제되었습니다.")

    return redirect('cart:list')


@login_required
@require_GET
def delete(request: HttpRequest, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)

    if cart_item.user != request.user:
        raise PermissionError()

    cart_item.delete()

    messages.success(request, "해당 장바구니 품목이 삭제되었습니다.")

    return redirect('cart:list')


@login_required
@require_POST
def modify(request: HttpRequest, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)

    if cart_item.user != request.user:
        raise PermissionError()

    cart_item.quantity = int(request.POST.get('quantity'))
    cart_item.save()

    messages.success(request, "해당 장바구니 품목의 개수가 수정되었습니다.")

    return redirect('cart:list')

cart/templates/cart/list.html
{% extends "layout.html" %}
{% load humanize %}

{%block content %}

<script>
    function CartItemModifyForm__updateQuantity(el, add) {
        const $form = $(el).closest('form');

        const $salePrice = $form.find('.cart-item-modify-form__sale-price');
        const productSalePrice = parseInt($salePrice.attr('data-sale-price'));
        const $inputNumber = $form.find('input[type="number"]');
        const oldQuantity = parseInt($inputNumber.val());
        const originQuantity = parseInt($inputNumber.attr('data-origin-value'));
        let newQuantity = oldQuantity + add;

        if ( newQuantity > 100 ) {
            newQuantity = 100;
        }
        else if ( newQuantity < 1 ) {
            newQuantity = 1
        }

        $inputNumber.val(newQuantity);
        $salePrice.text((productSalePrice * newQuantity).price_format());

        if ( originQuantity != newQuantity ) {
            $salePrice.addClass('t-text-red-400');
        }
        else {
            $salePrice.removeClass('t-text-red-400');
        }
    }

    function CartItems__allCheckBoxCheckChanged(el) {
        if ( el.checked ) {
            $('.cart-items__checkbox-item:not(:checked)').prop('checked', true);
        }
        else {
            $('.cart-items__checkbox-item:checked').prop('checked', false);
        }
    }

    function CartItems__itemCheckeChanged(el) {
        const allCheckBoxNewCheckStatus = $('.cart-items__checkbox-item:not(:checked)').length == 0;
        $('.cart-items__checkbox-all').prop('checked', allCheckBoxNewCheckStatus);
    }

    function CartItems__deleteChecked() {
        const cartItemIds = $('.cart-items__checkbox-item:checked')
            .map((i, el) => parseInt($(el).attr('data-id')))
            .toArray();

        CartItemsDeleteForm.ids.value = cartItemIds;
        CartItemsDeleteForm.submit();
    }


</script>

<section class="section-cart-item-list">
    <div class="container">
        <h1 class="t-font-bold">
            <i class="fas fa-shopping-cart"></i>

            <span>장바구니</span>
        </h1>

        {% if cart_items %}
        <hr>

        <div class="t-mt-[10px]">
            <label class="t-ml-[17px]">
                <input type="checkbox" class="cart-items__checkbox-all"
                       onchange="CartItems__allCheckBoxCheckChanged(this)">
                전체선택
            </label>
        </div>
        {% endif %}

        <hr>

        {% if cart_items %}
        <ul>
            {% for cart_item in cart_items %}
            <li class="t-py-[20px]">
                <div class="card">
                    <div class="card-body">
                        <div class="t-grid t-grid-cols-1 sm:t-grid-cols-[minmax(171px,_auto)_1fr] lg:t-grid-cols-[171px_1fr_auto] t-gap-3">
                            <div class="t-flex">
                                <input data-id="{{cart_item.id}}" type="checkbox" class="cart-items__checkbox-item"
                                       onchange="CartItems__itemCheckeChanged(this)">
                                <a href="{% url 'products:detail' cart_item.product_real.product.id %}" class="t-flex-shrink-0 box-border t-flex-grow">
                                    <img class="t-ml-2 t-w-[250px] t-h-[200px] sm:t-w-[150px] sm:t-h-[150px] t-object-cover rounded"
                                         src="{{cart_item.product_real.product.thumb_img_url}}" alt="">
                                </a>
                            </div>
                            <div class="t-flex t-flex-col t-items-start">
                                <div class="badge bg-primary">{{cart_item.product_real.product.market.name}}</div>
                                <div class="t-mt-[8px]">
                                    <span class="t-bg-[#ffe812] t-text-xs t-p-1 t-rounded">
                                        <i class="fas fa-comment"></i>
                                        <span class="t-font-bold">pay</span>
                                    </span>
                                    <a class="t-ml-2"
                                       href="{% url 'products:detail' cart_item.product_real.product.id %}">
                                        {{cart_item.product_real.product.display_name}}
                                    </a>
                                </div>
                                <div class="t-mt-[8px]">
                                    <span class="t-text-gray-500">{{ cart_item.product_real.product.sale_price|intcomma }}원</span>
                                    <span class="t-line-through t-text-gray-400">{{ cart_item.product_real.product.price|intcomma }}원</span>
                                </div>
                                <div class="t-mt-[5px] t-text-gray-500">
                                    <span>옵션 : </span>
                                    <span>{{cart_item.product_real.option_1_display_name}}</span>
                                    <span>/</span>
                                    <span>{{cart_item.product_real.option_2_display_name}}</span>
                                    <span class="t-inline-block t-rounded-full t-w-[10px] t-h-[10px]"
                                          style="background-color:#{{cart_item.product_real.rgb_color}}"></span>
                                </div>
                                <div class="t-mt-[5px] t-text-blue-400">
                                    <span><i class="fas fa-truck"></i> 오후 6시 주문, 당일출고</span>
                                </div>
                            </div>
                            <form class="sm:t-col-span-2 lg:t-col-span-1" method="POST" action="{% url 'cart:modify' cart_item.id %}" class="t-flex t-items-end">
                                {% csrf_token %}
                                <div>
                                    <div class="t-flex t-items-center t-gap-2">
                                    <span onclick="CartItemModifyForm__updateQuantity(this, -1)">
                                        <i class="fas fa-minus-circle"></i>
                                    </span>
                                        <input name="quantity" readonly min="1" max="100" class="form-control !t-w-[100px]"
                                               type="number" value="{{cart_item.quantity}}" data-origin-value="{{cart_item.quantity}}">
                                        <span onclick="CartItemModifyForm__updateQuantity(this, 1)">
                                        <i class="fas fa-plus-circle"></i>
                                    </span>
                                        <button type="submit" class="btn btn-primary btn-sm t-whitespace-nowrap">
                                            <i class="far fa-edit"></i>
                                            <span class="t-hidden sm:t-inline">수량수정</span>
                                        </button>
                                        <a onclick="if ( !confirm('정말 삭제하시겠습니까?') ) return false;"
                                           href="{% url 'cart:delete' cart_item.id %}" class="btn btn-danger btn-sm">
                                            <i class="far fa-trash-alt"></i>
                                            <span class="t-hidden sm:t-inline">삭제</span>
                                        </a>
                                    </div>
                                    <hr>
                                    <div class="t-flex-1"></div>
                                    <div>
                                        총 가격 :
                                        {% widthratio cart_item.quantity 1 cart_item.product_real.product.sale_price as total_price %}
                                        <span class="cart-item-modify-form__sale-price" data-sale-price="{{cart_item.product_real.product.sale_price}}">{{total_price|intcomma}}</span>원
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="t-text-center t-text-gray-400">
            <i class="far fa-sad-tear"></i>
            상품이 없습니다.<br>장바구니에 상품을 담아주세요.
        </div>
        {% endif %}

        {% if cart_items %}
        <hr>

        <div>
            <button type="button" class="btn btn-danger btn-sm" onclick="CartItems__deleteChecked();">선택삭제</button>
        </div>

        <form name="CartItemsDeleteForm" class="t-hidden" action="{% url 'cart:delete_items' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="ids" value="">
        </form>
        {% endif %}
    </div>
</section>

{%endblock%}