accounts/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from . import views
from .views import MyTokenObtainPairView

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),
    path('find_username/', views.find_username, name='find_username'),
    path('signin/kakao/', views.kakao_login, name="kakao_signin"),
    path('signin/kakao/callback/', views.kakao_login_callback, name="kakao_signin_callback"),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/access_token/', TokenRefreshView.as_view(), name='token_refresh_access_token'),
    path('api/token/refresh/refresh_token/', views.ApiRefreshRefreshTokenView.as_view(),
         name='token_refresh_refresh_token'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_pydenticon.views import image as pydenticon_image

from . import views


urlpatterns = [
    path('', views.index, name="main"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('qna/', include('qna.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
    path('identicon/image/<path:data>/', pydenticon_image, name='pydenticon_image'),
]
if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('list/', views.list, name='list'),
    path('delete/<int:cart_item_id>/', views.delete, name='delete'),
    path('modify/<int:cart_item_id>/', views.modify, name='modify'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:product_id>/', views.product_detail, name='detail'),
    path('<int:product_id>/question/create/', views.question_create, name='question_create'),
    path('<int:product_id>/question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    path('<int:product_id>/question/modify/<int:question_id>', views.question_modify, name='question_modify'),
    path('<int:product_id>/pick/', views.product_pick, name='pick'),
    path('<int:product_id>/picked/', views.product_unpick, name='unpick'),
    path('admin_api/', views.AdminApiProductListCreateView.as_view(), name='admin_api'),
    path('admin_api/<int:pk>/', views.AdminApiProductRetrieveUpdateDestroyView.as_view(), name='admin_api_item'),
    path('admin_api/<int:product_id>/reals/', views.AdminApiProductRealListCreateView.as_view(), name='admin_api_reals'),
]

qna/urls.py
app_name = 'qna'

urlpatterns = [

]

base/views.py
from django.http import HttpRequest
from django.shortcuts import render


def index(request: HttpRequest):
    return render(request, "home/main.html")

base/templates/layout.html
<!doctype html>
{% load static %}
{% load humanize %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{settings.SITE_NAME}} 입니다?????????</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'tailwind.output.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link rel="stylesheet" href="{% static 'common.css' %}">
    <script defer src="{% static 'common.js' %}"></script>


</head>
<body class="t-flex t-flex-col t-min-h-screen t-pt-[56px]">

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} t-my-[0px]">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main' %}"><i class="fab fa-pied-piper-hat"></i> 멋블리</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:list' %}"><i class="fas fa-tshirt"></i> 상품리스트</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:list' %}">
                            <i class="fas fa-shopping-cart"></i>
                            장바구니
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link !t-whitespace-nowrap" href="#">
                            <i class="far fa-user"></i>
                            {{user.name}}
                            <img class="t-w-[22px] t-h-[22px] t-rounded-full t-object-fit t-inline-block"
                                 src="{{ user.profile_img_url }}"/>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> 로그아웃</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:join' %}"><i class="fas fa-user-plus"></i> 회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:find_username' %}"><i class="fas fa-users"></i> 아이디찾기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{request.path}}"><i
                                class="fas fa-sign-in-alt"></i> 로그인</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex" action="{% url 'products:list'%}">
                    <input class="form-control me-2" type="search" name="search_keyword" placeholder="상품명을 입력해주세요."
                           aria-label="Search" value="{{request.GET.search_keyword}}">
                    <button class="btn btn-outline-success t-whitespace-nowrap" type="submit">검색</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<section class="t-flex-1 t-py-[20px] t-flex t-flex-col">
    {%block content%}
    {%endblock%}
</section>

<footer class="footer py-3 bg-light">
    <div class="container t-text-center">
        <span class="text-muted"><i class="fab fa-pied-piper-hat"></i> 멋블리</span>
    </div>
</footer>

</body>
</html>