accounts/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from . import views
from .views import MyTokenObtainPairView

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),
    path('find_username/', views.find_username, name='find_username'),
    path('signin/kakao/', views.kakao_login, name="kakao_signin"),
    path('signin/kakao/callback/', views.kakao_login_callback, name="kakao_signin_callback"),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/access_token/', TokenRefreshView.as_view(), name='token_refresh_access_token'),
    path('api/token/refresh/refresh_token/', views.ApiRefreshRefreshTokenView.as_view(),
         name='token_refresh_refresh_token'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

qna/urls.py
app_name = 'qna'

urlpatterns = [

]

accounts/models.py
import os
import random
from io import BytesIO
from urllib.parse import urlparse
from urllib.request import urlopen

from django.contrib.auth import login
from django.contrib.auth.models import AbstractUser
from django.core.files import File
from django.db import models
from django.db.models import QuerySet
from django.http import HttpRequest
from django.shortcuts import resolve_url


class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"

    class ProviderTypeCodeChoices(models.TextChoices):
        LOCAL = "local", "로컬"
        KAKAO = "kakao", "카카오"

    class Meta:
        ordering = ['-id']
        verbose_name = '회원들'
        verbose_name_plural = '회원'

    first_name = None
    last_name = None
    date_joined = None

    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)

    name = models.CharField('이름', max_length=100)
    gender = models.CharField('성별', max_length=1, blank=True, choices=GenderChoices.choices)
    profile_img = models.ImageField('프로필이미지', blank=True, upload_to="accounts/profile_img/%Y/%m/%d",
                                    help_text="gif/png/jpg 이미지를 업로드해주세요.")

    provider_type_code = models.CharField('프로바이더 타입코드', max_length=20, choices=ProviderTypeCodeChoices.choices,
                                          default=ProviderTypeCodeChoices.LOCAL)
    provider_accounts_id = models.PositiveIntegerField('프로바이더 회원번호', default=0)

    def __str__(self):
        return f"{self.id}, {self.username}"

    @staticmethod
    def login_with_kakao(request: HttpRequest, provider_accounts_id: int, provider_accounts_nickname: str,
                         provider_accounts_thumbnail_image_url: str):
        provider_type_code = User.ProviderTypeCodeChoices.KAKAO
        qs: QuerySet = User.objects.filter(provider_type_code=provider_type_code,
                                           provider_accounts_id=provider_accounts_id)

        if not qs.exists():
            username = provider_type_code + "__" + str(provider_accounts_id)
            name = provider_accounts_nickname if provider_accounts_nickname else username
            email = ""
            password = str(random.randint(1000, 9999))

            user: User = User.objects.create_user(username=username, email=email, password=password, name=name,
                                                  provider_type_code=provider_type_code,
                                                  provider_accounts_id=provider_accounts_id)

            if provider_accounts_thumbnail_image_url:
                provider_accounts_thumbnail_image_url_parsed = urlparse(provider_accounts_thumbnail_image_url)
                provider_accounts_thumbnail_image_file_name = os.path.basename(
                    provider_accounts_thumbnail_image_url_parsed.path)

                response = urlopen(provider_accounts_thumbnail_image_url)
                io = BytesIO(response.read())
                user.profile_img.save(provider_accounts_thumbnail_image_file_name, File(io))
        else:
            user: User = qs.first()

        login(request, user)

    @property
    def provider_link(self):
        if self.provider_type_code == 'kakao':
            return "https://developers.kakao.com"

        return "https://site7.public.473.be"

    @property
    def profile_img_url(self):
        if self.profile_img:
            return self.profile_img.url;
        return resolve_url('pydenticon_image', data=self.username)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from .models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].label = '아이디'


class FindUsernameForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True

    class Meta:
        model = User
        fields = ['name', 'email']


class JoinForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True
        self.fields['username'].label = '아이디'
        self.fields['profile_img'].widget.attrs['accept'] = 'image/png, image/gif, image/jpeg'

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'name', 'gender', 'profile_img']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

accounts/views.py
import os

import requests
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.views import (
    logout_then_login, LoginView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
from django.urls import reverse
from lazy_string import LazyString
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework_simplejwt.exceptions import TokenError, InvalidToken
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.views import TokenObtainPairView

from .decorators import logout_required
from .forms import JoinForm, FindUsernameForm, LoginForm
from .models import User
from .serializers import MyTokenObtainPairSerializer, ApiRefreshRefreshTokenSerializer


class MyLoginView(SuccessMessageMixin, LoginView):
    template_name = "accounts/login.html"
    next_page = "/"

    form_class = LoginForm

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        self.success_message = LazyString(
            lambda: f'{self.request.user.name}님 환영합니다.')

    def get_initial(self):
        initial = self.initial.copy()
        initial['username'] = self.request.GET.get('username', None)

        return initial


@logout_required
def login(request: HttpRequest):
    return MyLoginView.as_view()(request)


def logout(request: HttpRequest):
    messages.success(request, "로그아웃 되었습니다.")
    return logout_then_login(request)


@logout_required
def join(request: HttpRequest):
    if request.method == 'POST':
        form = JoinForm(request.POST, request.FILES)
        if form.is_valid():
            signed_user = form.save()
            auth_login(request, signed_user)
            messages.success(request, "회원가입 환영합니다.")
            next_url = request.GET.get('next', '/')
            return redirect(next_url)
    else:
        form = JoinForm()
    return render(request, 'accounts/join.html', {
        'form': form,
    })


@logout_required
def find_username(request: HttpRequest):
    if request.method == 'POST':
        form = FindUsernameForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']

            qs: QuerySet = User.objects.filter(email=email, name=name)

            if not qs.exists():
                messages.warning(request, "일치하는 회원이 존재하지 않습니다.")
            else:
                user: User = qs.first()
                messages.success(request, f"해당회원의 아이디는 {user.username} 입니다.")
                return redirect(reverse("accounts:login") + '?username=' + user.username)
    else:
        form = FindUsernameForm()

    return render(request, 'accounts/find_username.html', {
        'form': form,
    })


@logout_required
def kakao_login(request: HttpRequest):
    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")

    next = request.GET.get('next', '')
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code&state={next}"
    )


@logout_required
def kakao_login_callback(request):
    code = request.GET.get("code")

    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")

    token_request = requests.get(
        f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={code}"
    )

    token_json = token_request.json()

    error = token_json.get("error", None)
    if error is not None:
        raise Exception("카카오 로그인 에러")

    access_token = token_json.get("access_token")

    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    profile_json = profile_request.json()

    id = profile_json.get("id")
    profile: dict = profile_json.get("kakao_account").get("profile")

    nickname = profile.get("nickname", "")
    thumbnail_image_url = profile.get("thumbnail_image_url", "")

    User.login_with_kakao(request, id, nickname, thumbnail_image_url)

    messages.success(request, f"{nickname}님 환영합니다. 카카오톡 계정으로 로그인되었습니다")

    next = request.GET.get('state', '')

    return redirect("main" if not next else next)


# 이걸 사용하는 이유는 JWT 토큰안의 페이로드 안에 추가적인 내용(email, profile_img_url 등)을 담기 위함
class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer


# TODO 3주차 설명, 엑세스키와 리프레시키를 모두 재발급하는 로직이 필요합니다.
class ApiRefreshRefreshTokenView(GenericAPIView):
    permission_classes = ()  # 중요, 이렇게 해야 접근이 가능합니다.
    authentication_classes = ()  # 중요, 이렇게 해야 접근이 가능합니다.

    serializer_class = ApiRefreshRefreshTokenSerializer

    # 리프레시 토큰 자체를 다시 발급
    def post(self, request: HttpRequest):
        serializer: ApiRefreshRefreshTokenSerializer = self.get_serializer(data=request.data)

        serializer.is_valid(raise_exception=True)

        refresh: str = serializer.validated_data['refresh']

        try:
            refresh_token: RefreshToken = RefreshToken(refresh)
        except TokenError as e:
            raise InvalidToken(e)

        user: User = get_object_or_404(User, id=refresh_token['user_id'])
        new_refresh_token = MyTokenObtainPairSerializer.get_token(user)  # 이걸로 토큰을 생성해야 합니다. 다른 방법으로 하면 페이로드에 필수데이터가 누락된 버전이 생김
        new_access_token = new_refresh_token.access_token
        refresh_token.blacklist()  # 꼭 블랙리스트에 넣어주세요.

        return Response({
            'refresh': str(new_refresh_token),
            'access': str(new_access_token),
        })

accounts/templates/accounts/find_username.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}

<section class="section-signup t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header"><i class="fas fa-users"></i> 아이디찾기</div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="<i class='fas fa-users'></i> 아이디찾기" %}

                {% url 'main' as main_url %}
                {% bootstrap_button button_type="link" href=main_url content="취소" button_class="btn-outline-primary" %}

                {% url 'accounts:login' as accounts_login_url %}
                {% bootstrap_button button_type="link" href=accounts_login_url content="로그인" button_class="btn-outline-primary" %}
            </form>
        </div>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/join.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}

<section class="section-join t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header"><i class="fas fa-user-plus"></i> 회원가입</div>
        <div class="card-body">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="<i class='fas fa-user-plus'></i> 회원가입" %}

                {% url 'main' as main_url %}
                {% bootstrap_button button_type="link" href=main_url content="취소" button_class="btn-outline-primary" %}

                {% url 'accounts:login' as accounts_login_url %}
                {% bootstrap_button button_type="link" href=accounts_login_url content="로그인" button_class="btn-outline-primary" %}
            </form>
        </div>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}
<section class="section-login t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header">
            <i class="fas fa-sign-in-alt"></i> 로그인
        </div>
        <div class="card-body">
            <form method="POST" action="">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="<i class='fas fa-sign-in-alt'></i> 로그인" %}

                {% url 'main' as main_url %}
                {% bootstrap_button button_type="link" href=main_url content="취소" button_class="btn-outline-primary" %}

                {% url 'accounts:join' as accounts_join_url %}
                {% bootstrap_button button_type="link" href=accounts_join_url content="회원가입" button_class="btn-outline-primary" %}
            </form>
            <hr>
            <div class="t-py-2">
                <a class="t-text-black t-bg-[#ffe812] t-no-underline t-p-3 t-rounded hover:t-text-black hover:t-underline"
                   href="{% url 'accounts:kakao_signin' %}?next={{request.GET.next}}">
                    <i class="fas fa-comment"></i>
                    카카오 로그인
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}